In [ ]:
# contexte, but
# importer
# documentation officielle : https://numpy.org/doc/stable/
# np.<TAB>
# np?
# types en python, types en C / autres languages
# flexibilité python => probleme d'efficience calcul / mémoire
# d'où numpy
# exemples de création de numpy arrays
# multidimensional
# shape
# reshape
# slicing
# opérations vectorielles plutôt que par loop
# introduction à timeit

In [4]:
import numpy as np

In [5]:
np?

In [3]:
#/* C code */
#int x = 4;
#x = "four";  // FAILS

In [6]:
list?

In [7]:
l = ['a', 'b', 'c']

In [8]:
l.append('d')

In [9]:
l

['a', 'b', 'c', 'd']

In [10]:
# rapidité
# mémoire

In [12]:
a = np.array([1, 2, 3])

In [13]:
# taille du numpy array prédéfinie
# type prédéfini

In [14]:
x = 4
x = "four"

In [15]:
x

'four'

In [16]:
a = np.random.randn((4))

In [17]:
a

array([-0.80684246, -0.08624834,  0.57401856, -0.06737942])

In [29]:
b = np.random.randn(10000, 5)

In [27]:
a = np.array([i for i in range(10)])

In [28]:
a.shape

(10,)

In [30]:
b.shape

(10000, 5)

In [31]:
a.size

10

In [32]:
b.size

50000

In [34]:
b.reshape(5, 10000).shape

(5, 10000)

In [35]:
a = np.random.randn(3, 4)

In [36]:
a

array([[ 0.08767468, -1.82829091,  0.6651708 , -0.10561576],
       [ 0.46497012,  0.3026871 , -2.21405297, -0.49990687],
       [-1.53801836, -1.05846889,  0.26577903, -0.60547482]])

In [37]:
a.reshape(4, 3)

array([[ 0.08767468, -1.82829091,  0.6651708 ],
       [-0.10561576,  0.46497012,  0.3026871 ],
       [-2.21405297, -0.49990687, -1.53801836],
       [-1.05846889,  0.26577903, -0.60547482]])

In [38]:
a = np.random.randn(3, 4, 2)

In [39]:
a

array([[[ 1.84299486, -0.52219759],
        [-0.15828936,  1.30369003],
        [ 2.17648918,  0.61124415],
        [ 1.37088051,  0.01305769]],

       [[-1.49491583, -0.29682143],
        [ 0.64553436, -1.29936645],
        [ 1.61544278,  0.41496057],
        [-0.36161467, -1.68685843]],

       [[-0.03808522, -0.89459364],
        [ 0.8188355 ,  0.61277816],
        [ 0.98388048,  0.94009859],
        [ 2.29020248,  0.83150703]]])

In [41]:
a.reshape(4, 6, 1)

array([[[ 1.84299486],
        [-0.52219759],
        [-0.15828936],
        [ 1.30369003],
        [ 2.17648918],
        [ 0.61124415]],

       [[ 1.37088051],
        [ 0.01305769],
        [-1.49491583],
        [-0.29682143],
        [ 0.64553436],
        [-1.29936645]],

       [[ 1.61544278],
        [ 0.41496057],
        [-0.36161467],
        [-1.68685843],
        [-0.03808522],
        [-0.89459364]],

       [[ 0.8188355 ],
        [ 0.61277816],
        [ 0.98388048],
        [ 0.94009859],
        [ 2.29020248],
        [ 0.83150703]]])

In [42]:
a = np.random.randn(3, 4)

In [43]:
a

array([[ 0.53415317, -1.23933159,  1.0439839 ,  1.55211826],
       [-0.574413  , -0.35925168,  0.20132376, -1.42192064],
       [ 1.72057008,  1.49293207,  0.56108057, -1.69633467]])

In [44]:
a[1]

array([-0.574413  , -0.35925168,  0.20132376, -1.42192064])

In [45]:
a[:, 1]

array([-1.23933159, -0.35925168,  1.49293207])

In [46]:
a = np.random.randn(3, 4, 5)

In [48]:
a[:, :, 2]

array([[-0.03639695,  0.43956994, -0.23340556, -1.18613459],
       [-0.87798002,  0.27093235, -1.27351848,  1.01642122],
       [ 1.57365481, -0.39877049, -0.9020987 ,  0.33004906]])

In [49]:
a[0, 0, 0]

-0.21275552925101218

In [50]:
a.dtype

dtype('float64')

In [53]:
a = np.array([1.0, 2.0, 3.0])

In [54]:
a.dtype

dtype('float64')

In [55]:
a = np.random.randn(10, 10)

In [56]:
a

array([[ 0.01790504,  1.38471933, -1.24762113,  1.94878761, -0.39932786,
        -1.02017731, -0.48037653,  0.1299199 , -1.12633862,  0.27541865],
       [ 0.50700615,  0.4412827 , -0.21676679,  1.13266109, -0.60439627,
         1.00700415,  0.75648164,  0.04734681, -0.10814855,  1.30736021],
       [ 0.30190919, -0.34119907,  0.0275983 ,  0.07934843,  1.7488312 ,
        -1.45082758, -2.27355305,  0.19273898, -1.54700221, -1.83784897],
       [-0.92559332, -1.32614435,  1.48144949, -2.0683257 , -0.29627826,
        -0.96405445, -0.12809929,  0.07823511, -2.15243158,  0.23195074],
       [-0.00868524,  1.56916613,  0.09340131, -0.40815302,  0.38508768,
        -0.95374471,  0.31667281,  0.13750598, -0.79116042,  0.23882476],
       [ 0.38129713, -0.60746903,  2.24416182,  0.14224216, -0.43538787,
        -0.41621806,  1.51669899,  0.24214842,  1.60871078,  0.1745198 ],
       [ 0.44730789,  0.06038855,  0.656692  ,  1.16135576, -1.81282879,
        -1.85826438, -0.20961164, -0.49770365

In [60]:
c = a[2:4, 3:5]

In [62]:
c

array([[ 0.07934843,  1.7488312 ],
       [-2.0683257 , -0.29627826]])

In [63]:
c + 1 

array([[ 1.07934843,  2.7488312 ],
       [-1.0683257 ,  0.70372174]])

In [64]:
c = c + 1

In [65]:
c

array([[ 1.07934843,  2.7488312 ],
       [-1.0683257 ,  0.70372174]])

In [66]:
a[2:4, 3:5]

array([[ 0.07934843,  1.7488312 ],
       [-2.0683257 , -0.29627826]])

In [67]:
a = a + 1

In [68]:
c

array([[ 1.07934843,  2.7488312 ],
       [-1.0683257 ,  0.70372174]])

In [69]:
b = np.random.randn(3, 3)

In [70]:
b

array([[ 0.75838241, -0.36099838,  1.44695918],
       [ 0.69031305,  0.14805305, -0.74208073],
       [ 0.11407458,  0.95071707, -0.85914007]])

In [71]:
c = b[1:, 1:]

In [72]:
c

array([[ 0.14805305, -0.74208073],
       [ 0.95071707, -0.85914007]])

In [73]:
b = b + 1

In [74]:
b

array([[1.75838241, 0.63900162, 2.44695918],
       [1.69031305, 1.14805305, 0.25791927],
       [1.11407458, 1.95071707, 0.14085993]])

In [75]:
c

array([[ 0.14805305, -0.74208073],
       [ 0.95071707, -0.85914007]])

In [76]:
b = np.array([i for i in range(10)])

In [77]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
a

array([[ 1.01790504,  2.38471933, -0.24762113,  2.94878761,  0.60067214,
        -0.02017731,  0.51962347,  1.1299199 , -0.12633862,  1.27541865],
       [ 1.50700615,  1.4412827 ,  0.78323321,  2.13266109,  0.39560373,
         2.00700415,  1.75648164,  1.04734681,  0.89185145,  2.30736021],
       [ 1.30190919,  0.65880093,  1.0275983 ,  1.07934843,  2.7488312 ,
        -0.45082758, -1.27355305,  1.19273898, -0.54700221, -0.83784897],
       [ 0.07440668, -0.32614435,  2.48144949, -1.0683257 ,  0.70372174,
         0.03594555,  0.87190071,  1.07823511, -1.15243158,  1.23195074],
       [ 0.99131476,  2.56916613,  1.09340131,  0.59184698,  1.38508768,
         0.04625529,  1.31667281,  1.13750598,  0.20883958,  1.23882476],
       [ 1.38129713,  0.39253097,  3.24416182,  1.14224216,  0.56461213,
         0.58378194,  2.51669899,  1.24214842,  2.60871078,  1.1745198 ],
       [ 1.44730789,  1.06038855,  1.656692  ,  2.16135576, -0.81282879,
        -0.85826438,  0.79038836,  0.50229635

In [80]:
a + 1

array([[ 2.01790504,  3.38471933,  0.75237887,  3.94878761,  1.60067214,
         0.97982269,  1.51962347,  2.1299199 ,  0.87366138,  2.27541865],
       [ 2.50700615,  2.4412827 ,  1.78323321,  3.13266109,  1.39560373,
         3.00700415,  2.75648164,  2.04734681,  1.89185145,  3.30736021],
       [ 2.30190919,  1.65880093,  2.0275983 ,  2.07934843,  3.7488312 ,
         0.54917242, -0.27355305,  2.19273898,  0.45299779,  0.16215103],
       [ 1.07440668,  0.67385565,  3.48144949, -0.0683257 ,  1.70372174,
         1.03594555,  1.87190071,  2.07823511, -0.15243158,  2.23195074],
       [ 1.99131476,  3.56916613,  2.09340131,  1.59184698,  2.38508768,
         1.04625529,  2.31667281,  2.13750598,  1.20883958,  2.23882476],
       [ 2.38129713,  1.39253097,  4.24416182,  2.14224216,  1.56461213,
         1.58378194,  3.51669899,  2.24214842,  3.60871078,  2.1745198 ],
       [ 2.44730789,  2.06038855,  2.656692  ,  3.16135576,  0.18717121,
         0.14173562,  1.79038836,  1.50229635

In [81]:
a - 1

array([[ 0.01790504,  1.38471933, -1.24762113,  1.94878761, -0.39932786,
        -1.02017731, -0.48037653,  0.1299199 , -1.12633862,  0.27541865],
       [ 0.50700615,  0.4412827 , -0.21676679,  1.13266109, -0.60439627,
         1.00700415,  0.75648164,  0.04734681, -0.10814855,  1.30736021],
       [ 0.30190919, -0.34119907,  0.0275983 ,  0.07934843,  1.7488312 ,
        -1.45082758, -2.27355305,  0.19273898, -1.54700221, -1.83784897],
       [-0.92559332, -1.32614435,  1.48144949, -2.0683257 , -0.29627826,
        -0.96405445, -0.12809929,  0.07823511, -2.15243158,  0.23195074],
       [-0.00868524,  1.56916613,  0.09340131, -0.40815302,  0.38508768,
        -0.95374471,  0.31667281,  0.13750598, -0.79116042,  0.23882476],
       [ 0.38129713, -0.60746903,  2.24416182,  0.14224216, -0.43538787,
        -0.41621806,  1.51669899,  0.24214842,  1.60871078,  0.1745198 ],
       [ 0.44730789,  0.06038855,  0.656692  ,  1.16135576, -1.81282879,
        -1.85826438, -0.20961164, -0.49770365

In [82]:
a * 2

array([[ 2.03581009,  4.76943867, -0.49524226,  5.89757523,  1.20134427,
        -0.04035463,  1.03924694,  2.2598398 , -0.25267725,  2.5508373 ],
       [ 3.01401229,  2.8825654 ,  1.56646642,  4.26532217,  0.79120746,
         4.0140083 ,  3.51296328,  2.09469361,  1.78370291,  4.61472042],
       [ 2.60381839,  1.31760186,  2.05519659,  2.15869686,  5.4976624 ,
        -0.90165516, -2.5471061 ,  2.38547795, -1.09400442, -1.67569795],
       [ 0.14881336, -0.65228869,  4.96289897, -2.1366514 ,  1.40744349,
         0.0718911 ,  1.74380142,  2.15647023, -2.30486315,  2.46390147],
       [ 1.98262952,  5.13833225,  2.18680263,  1.18369395,  2.77017537,
         0.09251057,  2.63334562,  2.27501197,  0.41767916,  2.47764952],
       [ 2.76259426,  0.78506194,  6.48832363,  2.28448432,  1.12922426,
         1.16756388,  5.03339798,  2.48429685,  5.21742156,  2.34903961],
       [ 2.89461577,  2.1207771 ,  3.313384  ,  4.32271151, -1.62565759,
        -1.71652877,  1.58077672,  1.00459271

In [83]:
a / 2

array([[ 0.50895252,  1.19235967, -0.12381056,  1.47439381,  0.30033607,
        -0.01008866,  0.25981173,  0.56495995, -0.06316931,  0.63770933],
       [ 0.75350307,  0.72064135,  0.3916166 ,  1.06633054,  0.19780187,
         1.00350207,  0.87824082,  0.5236734 ,  0.44592573,  1.15368011],
       [ 0.6509546 ,  0.32940046,  0.51379915,  0.53967422,  1.3744156 ,
        -0.22541379, -0.63677652,  0.59636949, -0.2735011 , -0.41892449],
       [ 0.03720334, -0.16307217,  1.24072474, -0.53416285,  0.35186087,
         0.01797278,  0.43595036,  0.53911756, -0.57621579,  0.61597537],
       [ 0.49565738,  1.28458306,  0.54670066,  0.29592349,  0.69254384,
         0.02312764,  0.65833641,  0.56875299,  0.10441979,  0.61941238],
       [ 0.69064857,  0.19626548,  1.62208091,  0.57112108,  0.28230607,
         0.29189097,  1.2583495 ,  0.62107421,  1.30435539,  0.5872599 ],
       [ 0.72365394,  0.53019428,  0.828346  ,  1.08067788, -0.4064144 ,
        -0.42913219,  0.39519418,  0.25114818

In [84]:
b = np.random.randn(10, 10)

In [85]:
a + b

array([[ 0.83392186,  1.78677778, -2.84799224,  3.13466328, -1.58562325,
        -1.37669697,  1.21894077,  0.047534  , -1.33443132,  2.10376189],
       [ 1.14095702,  1.15421404,  2.00304356,  1.59112892,  1.173153  ,
         1.84839385,  1.87305461,  0.1879789 ,  1.45102401,  0.49607282],
       [ 2.02199476,  1.18196186, -0.00564796,  1.35813028,  3.47816378,
        -0.203573  , -0.5798914 ,  2.89307905,  0.6499875 , -2.00843681],
       [ 0.58875698,  0.23353951,  1.63054244, -1.00172992,  0.73828524,
         0.87979077, -0.16885862,  2.41010267, -1.20320842,  2.08697797],
       [ 2.23347944,  3.08130339, -0.07517416,  0.91444861,  2.0236483 ,
        -1.8132311 ,  0.0993491 ,  1.81665067, -0.1843245 ,  1.57565636],
       [ 0.65896952,  0.08153589,  4.36527859,  1.18963599, -0.15142815,
         0.07854479,  1.43731512,  1.86260949,  1.92719402,  1.75052965],
       [ 1.95602346,  2.51863975,  2.80619058,  4.05912169, -1.12845615,
        -2.83454405,  0.79078336,  0.71831582

In [86]:
a - b

array([[ 1.20188823,  2.98266089,  2.35274998,  2.76291195,  2.78696753,
         1.33634235, -0.17969383,  2.2123058 ,  1.08175407,  0.44707542],
       [ 1.87305527,  1.72835136, -0.43657714,  2.67419326, -0.38194554,
         2.16561444,  1.63990867,  1.90671471,  0.3326789 ,  4.1186476 ],
       [ 0.58182362,  0.13564   ,  2.06084455,  0.80056658,  2.01949862,
        -0.69808216, -1.96721469, -0.5076011 , -1.74399192,  0.33273886],
       [-0.43994362, -0.8858282 ,  3.33235653, -1.13492148,  0.66915824,
        -0.80789967,  1.91266004, -0.25363244, -1.10165473,  0.3769235 ],
       [-0.25084992,  2.05702886,  2.26197679,  0.26924534,  0.74652707,
         1.90574168,  2.53399653,  0.4583613 ,  0.60200366,  0.90199317],
       [ 2.10362474,  0.70352605,  2.12304504,  1.09484833,  1.28065242,
         1.0890191 ,  3.59608286,  0.62168736,  3.29022754,  0.59850996],
       [ 0.93859231, -0.39786265,  0.50719342,  0.26358983, -0.49720144,
         1.11801528,  0.78999336,  0.28627689

In [87]:
a * b

array([[-1.87277412e-01, -1.42592278e+00,  6.43906832e-01,
         5.48107867e-01, -1.31324672e+00,  2.73709222e-02,
         3.63381681e-01, -1.22300937e+00,  1.52628768e-01,
         1.05648441e+00],
       [-5.51638287e-01, -4.13747089e-01,  9.55395973e-01,
        -1.15490458e+00,  3.07601394e-01, -3.18331522e-01,
         2.04758279e-01, -9.00056232e-01,  4.98698859e-01,
        -4.17929245e+00],
       [ 9.37486024e-01,  3.44658906e-01, -1.06176209e+00,
         3.00902750e-01,  2.00481216e+00, -1.11469185e-01,
        -8.83414902e-01,  2.02806188e+00, -6.54756018e-01,
         9.80775817e-01],
       [ 3.82710978e-02, -1.82537725e-01, -2.11148285e+00,
        -7.11459880e-02,  2.43230870e-02,  3.03324815e-02,
        -9.07438801e-01,  1.43606636e+00,  5.85168383e-02,
         1.05335143e+00],
       [ 1.23137618e+00,  1.31576572e+00, -1.27772196e+00,
         1.90930804e-01,  8.84462450e-01, -8.60110757e-02,
        -1.60281704e+00,  7.72531142e-01, -8.21082212e-02,
         4.

In [88]:
a / b

array([[-5.53259823e+00, -3.98821478e+00,  9.52253040e-02,
         1.58643014e+01, -2.74744273e-01,  1.48743243e-02,
         7.43043920e-01, -1.04391594e+00,  1.04576928e-01,
         1.53972242e+00],
       [-4.11695050e+00, -5.02068988e+00,  6.42094247e-01,
        -3.93819834e+00,  5.08782846e-01, -1.26536814e+01,
         1.50676582e+01, -1.21874089e+00,  1.59494854e+00,
        -1.27387858e+00],
       [ 1.80799234e+00,  1.25927013e+00, -9.94533773e-01,
         3.87165964e+00,  3.76896806e+00, -1.82333357e+00,
        -1.83598597e+00,  7.01470836e-01, -4.56981546e-01,
         7.15750624e-01],
       [ 1.44661486e-01, -5.82729598e-01, -2.91624038e+00,
        -1.60419418e+01,  2.03602565e+01,  4.25973273e-02,
        -8.37754405e-01,  8.09566321e-01,  2.26960064e+01,
         1.44083216e+00],
       [ 7.98054213e-01,  5.01655762e+00, -9.35670258e-01,
         1.83460623e+00,  2.16907783e+00, -2.48753025e-02,
        -1.08161272e+00,  1.67490965e+00, -5.31176646e-01,
         3.

In [89]:
a = np.random.randn(3)

In [90]:
b = np.random.randn(4)

In [91]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [97]:
a = np.arange(10)

In [100]:
a = a.reshape(5, 2)

In [102]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [101]:
np.sum(a, axis=0)

array([20, 25])

In [103]:
np.sum(a, axis=1)

array([ 1,  5,  9, 13, 17])

In [104]:
np.sum(a)

45

In [105]:
np.mean(a)

4.5

In [106]:
np.mean(a, axis=0)

array([4., 5.])

In [107]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [118]:
l = [i + 1 for i in range(10000)]

In [119]:
%timeit la = [1 / i for i in l]

788 µs ± 165 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [112]:
la

[1.0,
 0.5,
 0.3333333333333333,
 0.25,
 0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1,
 0.09090909090909091,
 0.08333333333333333,
 0.07692307692307693,
 0.07142857142857142,
 0.06666666666666667,
 0.0625,
 0.058823529411764705,
 0.05555555555555555,
 0.05263157894736842,
 0.05,
 0.047619047619047616,
 0.045454545454545456,
 0.043478260869565216,
 0.041666666666666664,
 0.04,
 0.038461538461538464,
 0.037037037037037035,
 0.03571428571428571,
 0.034482758620689655,
 0.03333333333333333,
 0.03225806451612903,
 0.03125,
 0.030303030303030304,
 0.029411764705882353,
 0.02857142857142857,
 0.027777777777777776,
 0.02702702702702703,
 0.02631578947368421,
 0.02564102564102564,
 0.025,
 0.024390243902439025,
 0.023809523809523808,
 0.023255813953488372,
 0.022727272727272728,
 0.022222222222222223,
 0.021739130434782608,
 0.02127659574468085,
 0.020833333333333332,
 0.02040816326530612,
 0.02,
 0.0196078431372549,
 0.019230769230769232,
 0.01886792452830

In [120]:
nl = np.array(l)

In [121]:
nl

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [122]:
%timeit 1 / nl

31.6 µs ± 3.42 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [123]:
31/788

0.03934010152284264

In [124]:
np.__version__

'1.18.5'

In [136]:
import numpy as np
a = np.array([1, 2, 3])
b = a
c = np.copy(a) #same as a.copy()
a[0] = 0
print(a, b, c)

[0 2 3] [0 2 3] [1 2 3]


In [138]:
a[2] = 2

In [139]:
b

array([0, 2, 2])

In [128]:
b

array([1, 3, 4])

In [129]:
a = a + 1

In [130]:
b

array([1, 3, 4])

In [131]:
a

array([1, 3, 4])

In [141]:
import numpy as np
a = np.array([1, 2, 3])
b = a
c = np.copy(a) #same as a.copy()
a[0] = 0
print(a, b, c)
a = a + 1
print(a, b)
b = a
a[1] = 6
print(a, b)

[0 2 3] [0 2 3] [1 2 3]
[1 3 4] [0 2 3]
[1 6 4] [1 6 4]


In [142]:
np.empty

<function numpy.empty>

In [151]:
a = np.random.randn(3, 4)

In [180]:
a[(a < 1) | (a > 0)]

array([-0.09623913, -0.27556583, -0.55252647, -0.19552415, -0.65301004,
       25.        ,  1.20477165, -0.64788757, -1.07106451, -1.42707811,
       -0.22795915, 25.        ])

In [168]:
b[(a < 1) & (a > 0)] = 25

In [162]:
a

array([[-0.09623913, -0.27556583, -0.55252647, -0.19552415],
       [-0.65301004, 25.        ,  1.20477165, -0.64788757],
       [-1.07106451, -1.42707811, -0.22795915, 25.        ]])

In [165]:
b = np.empty((3, 4))

In [169]:
b

array([[ 0.09623913,  0.27556583,  0.55252647,  0.19552415],
       [ 0.65301004, 25.        ,  1.20477165,  0.64788757],
       [ 1.07106451,  1.42707811,  0.22795915, 25.        ]])

In [170]:
b[:2]

array([[ 0.09623913,  0.27556583,  0.55252647,  0.19552415],
       [ 0.65301004, 25.        ,  1.20477165,  0.64788757]])

In [171]:
b[2, :2]

array([1.07106451, 1.42707811])

In [172]:
b[np.array([[True, True], [False, True]])]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2

In [173]:
b = np.random.randn(2, 2)

In [174]:
b[np.array([[True, True], [False, True]])]

array([-0.68600989, -1.83762588, -1.43423865])

In [175]:
np.array([[True, True], [False, True]])

array([[ True,  True],
       [False,  True]])

array([[-0.68600989, -1.83762588],
       [ 0.90021289, -1.43423865]])

In [182]:
a = np.random.randn(3, 4)

In [183]:
a

array([[-0.9036506 ,  0.14222481,  2.31490033, -0.28147785],
       [-0.61169523,  1.2491824 , -1.28888952,  0.20001599],
       [-0.64465511, -1.47336766, -0.54140581, -0.68606849]])

In [186]:
a[:2, :3]

array([[-0.9036506 ,  0.14222481,  2.31490033],
       [-0.61169523,  1.2491824 , -1.28888952]])

In [194]:
a = np.random.randn(2, 2)

In [191]:
a[np.array([[True, True], [False, True]])] = 2

In [192]:
a

array([[ 2.        ,  2.        ],
       [-1.10202236,  2.        ]])

In [193]:
a

array([[ 2.        ,  2.        ],
       [-1.10202236,  2.        ]])

In [195]:
a

array([[ 1.43856247, -0.06083495],
       [-0.69574683, -2.58446192]])

In [198]:
a[a > 0.5] = 1

In [199]:
a

array([[ 1.        , -0.06083495],
       [-0.69574683, -2.58446192]])

In [200]:
a = np.random.randn(3, 4)

In [201]:
a

array([[ 0.1555532 ,  1.06323427,  1.09526378, -0.0614913 ],
       [-1.55381471, -0.13112357, -1.67537979, -1.75691915],
       [-0.78283502, -1.06382169,  0.0567528 ,  1.15464026]])

In [204]:
(a > 0) | (a < 1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [205]:
a = np.random.randn(3, 4)

In [206]:
a

array([[-0.09363458, -1.49254784, -0.16924554, -0.17363571],
       [ 1.0699141 , -0.4244834 , -0.45618223,  0.23303359],
       [-1.06465359, -0.29835516,  1.35534525,  1.18553357]])

In [207]:
a[:2, :3]

array([[-0.09363458, -1.49254784, -0.16924554],
       [ 1.0699141 , -0.4244834 , -0.45618223]])

In [208]:
a = np.random.randn(2, 2)

In [209]:
a

array([[ 0.74479437, -0.1532996 ],
       [ 0.35362647, -0.92292142]])

In [210]:
b = np.array([[True, False], [False, True]])

In [211]:
b

array([[ True, False],
       [False,  True]])

In [213]:
a[b] = 2

In [214]:
a

array([[ 2.        , -0.1532996 ],
       [ 0.35362647,  2.        ]])

In [215]:
#advanced indexing

In [216]:
a = np.random.randn(3, 4)

In [218]:
a > 0

array([[ True, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [219]:
a

array([[ 1.3465715 , -0.74516078,  0.6023246 , -0.83954565],
       [-1.49973027,  0.70516735, -0.26923573, -1.16965989],
       [-0.99806997, -0.93480117, -0.01922274, -0.99054757]])

In [220]:
a > 1

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [221]:
(a > 0) & (a < 1)

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [255]:
a = np.random.randn(2, 3)

In [238]:
a

array([[-1.22492844,  0.39587192, -0.13658666],
       [-0.65540764,  0.45161771,  0.14770695]])

In [256]:
b = np.empty((2, 3))

In [240]:
def test_jm():
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if a[i, j] > 0:
                b[i, j] = 1
            else:
                b[i, j] = -1

In [241]:
%timeit test_jm()

6.13 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [244]:
a > 0

array([[False,  True, False],
       [False,  True,  True]])

In [245]:
a[:2,1]

array([0.39587192, 0.45161771])

In [251]:
b[a > 0] = 1

In [252]:
b[a < 0] = -1

In [254]:
b

array([[-1.,  1., -1.],
       [-1.,  1.,  1.]])

In [257]:
def test_jm2():
    b[a > 0] = 1
    b[a < 0] = -1

In [258]:
%timeit test_jm2()

5.09 µs ± 742 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [260]:
b[(a > 0) & (a < 1)] = 

array([1., 1.])

In [270]:
a = np.random.randn(2000, 3000)
b = np.empty((2000, 3000))
def test_jm(x, y):
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i, j] > 0:
                y[i, j] = 1
            else:
                y[i, j] = -1

In [271]:
%timeit test_jm(a, b)

4.12 s ± 65.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [274]:
a = np.random.randn(2000, 3000)
b = np.empty((2000, 3000))
def test_jm_2(x, y):
    y[x > 0] = 1
    y[x < 0] = -1

In [275]:
%timeit test_jm_2(a, b)

82.4 ms ± 5.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [280]:
4 / (82.4 * 10**(-3) )

48.543689320388346

In [281]:
a > 0 & a < 1

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''